//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargaPagosCGP
    {
        public int IdRegistro { get; set; }
        public string IdDestino { get; set; }
        public string TitularServicio { get; set; }
        public string CuentaClienteDestino { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string IdUsuario { get; set; }
    }
}
