//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CoopeBankEntities : DbContext
    {
        public CoopeBankEntities()
            : base("name=CoopeBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AHORROS_BIT_TRAS> AHORROS_BIT_TRAS { get; set; }
        public virtual DbSet<Modulos> Modulos { get; set; }
        public virtual DbSet<Pantallas> Pantallas { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<SubOpciones> SubOpciones { get; set; }
        public virtual DbSet<TipoServicioSinpe> TipoServicioSinpe { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<vTipoNomina> vTipoNomina { get; set; }
        public virtual DbSet<CargaPagosCGP> CargaPagosCGP { get; set; }
        public virtual DbSet<ParametrosArcCGP> ParametrosArcCGP { get; set; }
    
        public virtual ObjectResult<consultarPagosCGP_Result> consultarPagosCGP(string tipoPago)
        {
            var tipoPagoParameter = tipoPago != null ?
                new ObjectParameter("tipoPago", tipoPago) :
                new ObjectParameter("tipoPago", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<consultarPagosCGP_Result>("consultarPagosCGP", tipoPagoParameter);
        }
    
        public virtual ObjectResult<consultarNominaPago_Result> consultarNominaPago(Nullable<System.DateTime> fechaPago, string tipoNomina)
        {
            var fechaPagoParameter = fechaPago.HasValue ?
                new ObjectParameter("fechaPago", fechaPago) :
                new ObjectParameter("fechaPago", typeof(System.DateTime));
    
            var tipoNominaParameter = tipoNomina != null ?
                new ObjectParameter("tipoNomina", tipoNomina) :
                new ObjectParameter("tipoNomina", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<consultarNominaPago_Result>("consultarNominaPago", fechaPagoParameter, tipoNominaParameter);
        }
    }
}
